# Spring Boot + Spring LDAP configuration application.yml

spring:
  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
    # urls: ldap://localhost:12345
    # base: dc=memorynotfound,dc=com
    # username: uid=admin
    # password: secret

    # Embedded Spring LDAP
    embedded:
      base-dn: dc=mariodan,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:users-ldap.ldif
      port: 8389
      validation:
        enabled: false