
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'


  health:
    ldap:
      enabled: false


services:
  auth-service:
    url: http://localhost
    urlPath: /v1/user/profile
  user-profile:
    url: https://openexchangerates.org/api/currencies.json